---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brokencrystals.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "brokencrystals.fullname" . }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ include "brokencrystals.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "brokencrystals.fullname" . }}-postgres
    spec:
      containers:
        - name: {{ include "brokencrystals.fullname" . }}-postgres
          image: postgres
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: POSTGRES_DB
              value: "bc"
            - name: POSTGRES_USER
              value: "bc"
            - name: POSTGRES_PASSWORD
              value: "bc"
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
          - name: {{ include "brokencrystals.fullname" . }}-postgres
            mountPath: /docker-entrypoint-initdb.d/pg.sql
            subPath: pg.sql
            readOnly: true
      volumes:
      - name: {{ include "brokencrystals.fullname" . }}-postgres
        configMap:
          name: {{ include "brokencrystals.fullname" . }}-postgres


---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "brokencrystals.fullname" . }}-postgres-nodejs
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "brokencrystals.fullname" . }}-postgres
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432

