name: Release Charts

on:
  push:
    branches:
      - master
      - development
      - experimental

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          git config --global user.email "devops@brightsec.com"
          git config --global user.name "Bright Security"

      - name: Change name to development
        if: ${{ github.ref == 'refs/heads/development' }}
        run: |          
          sed -i 's/brokencrystals/brokencrystals-dev/g' ./charts/brokencrystals/Chart.yaml
          sed -i 's/brkn/brkn-dev/g' ./charts/brokencrystals/Chart.yaml

      - name: Change values to development
        if: ${{ github.ref == 'refs/heads/development' }}
        run: |          
          sed -i 's/^  main:.*/  main: development/' ./charts/brokencrystals/values.yaml
          sed -i 's/^  client:.*/  client: development/' ./charts/brokencrystals/values.yaml
          
      - name: Release packages
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true


